import React, { createContext, useState, useContext, useEffect } from 'react';

// Comprehensive Marathi translation dictionary for instant (no-API) switching
const marathiDict = {
  // CRITICAL: Smart Advisor Strings (Priority)
  'SMART ADVISORY HUB v3.0': 'स्मार्ट सल्लागार केंद्र v3.0',
  'Plan Your Success': 'तुमचे यश नियोजित करा',
  'Smarter & Better': 'अधिक स्मार्ट आणि चांगले',
  'Crop Recommendation': 'पीक शिफारस',
  'Agri Calculator': 'कृषी गणकयंत्र',
  'Requirement Analysis': 'गरज विश्लेषण',
  'Total Requirement': 'एकूण गरज',
  'Estimated Cost': 'अंदाजित खर्च',
  'Analyze My Needs': 'माझ्या गरजा तपासा',
  'Recommended Crops': 'शिफारस केलेली पिके',
  'Yield Potential': 'उत्पादन क्षमता',
  'Estimated Profit': 'अंदाजित नफा',
  'Match': 'सुसंगतता',
  'View Cultivation Guide': 'लागवड मार्गदर्शक पहा',
  'Expert Advice Note': 'तज्ज्ञ सल्ला टीप',
  'These calculations and recommendations are based on regional averages and historical data. For best results, we recommend local soil testing and consulting with an agricultural expert before making large investments.': 'हे हिशोब आणि शिफारसी प्रादेशिक सरासरी आणि ऐतिहासिक डेटावर आधारित आहेत. सर्वोत्तम निकालांसाठी, आम्ही मोठ्या गुंतवणुकीपूर्वी स्थानिक माती परीक्षण आणि कृषी तज्ज्ञांचा सल्ला घेण्याची शिफारस करतो.',

  // Navigation
  'Home': 'मुख्य पान', 'Farming Basics': 'शेतीची माहिती', 'Crop Guide': 'पीक सल्ला',
  'Calculator': 'हिशोब', 'Calendar': 'कॅलेंडर', 'Schemes': 'सरकारी योजना',
  'Videos': 'व्हिडिओ', 'Help': 'मदत', 'Profile': 'माझी माहिती',
  'Login': 'लॉगिन', 'Register': 'नोंदणी', 'Logout': 'बाहेर पडा',

  // Districts & Seasons
  'District': 'जिल्हा',
  'Pune': 'पुणे', 'Nashik': 'नाशिक', 'Kolhapur': 'कोल्हापूर', 'Sangli': 'सांगली', 
  'Solapur': 'सोलापूर', 'Ahmednagar': 'अहमदनगर', 'Aurangabad': 'छत्रपती संभाजीनगर', 'Satara': 'सातारा',
  'Season': 'हंगाम',
  'Kharif': 'खरीप', 'Rabi': 'रब्बी', 'Summer': 'उन्हाळा',
  'Kharif (Monsoon)': 'खरीप (पावसाळा)', 'Rabi (Winter)': 'रब्बी (हिवाळा)',

  // Units
  't/ha': 'टन/हेक्टर', 'Lakh/ha': 'लाख/हेक्टर', 'Lakh': 'लाख', 'tonnes': 'टन', 'acre': 'एकर', 'hectare': 'हेक्टर',

  // Home page
  'Welcome to Smart Farming': 'स्मार्ट शेतीमध्ये स्वागत आहे',
  'Grow Smarter with': 'अधिक हुशारीने वाढवा',
  'Your AI-powered farming companion for higher yields and better profits': 'जास्त उत्पन्न आणि नफ्यासाठी तुमचा AI शेती साथीदार',
  'Start Farming Journey': 'शेती सुरू करा', 'Learn More': 'अधिक जाणा',
  'Smart Farming Solutions': 'स्मार्ट शेती उपाय',
  'Everything you need to succeed in modern agriculture': 'आधुनिक शेतीत यशस्वी होण्यासाठी सर्वकाही',
  'Crop Guides': 'पीक मार्गदर्शन', 'Expert guides for Sugarcane & Grapes': 'उस आणि द्राक्षासाठी तज्ज्ञ मार्गदर्शन',
  'Cost Calculator': 'खर्च हिशोब', 'Calculate profits & investments': 'नफा आणि गुंतवणूक मोजा',
  'Crop Calendar': 'पीक कॅलेंडर', 'Monthly farming activities': 'मासिक शेती कामे',
  'Govt Schemes': 'सरकारी योजना', 'Latest agriculture schemes': 'नवीनतम कृषी योजना',
  'Video Learning': 'व्हिडिओ शिक्षण', 'Watch farming tutorials': 'शेती ट्युटोरियल पहा',
  '24/7 Support': '२४/७ मदत', 'Get farming assistance': 'शेती मदत मिळवा',
  'Active Farmers': 'सक्रिय शेतकरी', 'Expert Guides': 'तज्ज्ञ मार्गदर्शन',
  'Satisfaction Rate': 'समाधान दर',
  'Ready to Transform Your Farming?': 'तुमची शेती बदलण्यास तयार आहात?',
  'Join thousands of farmers already using Smart Krishi to increase their yields': 'स्मार्ट कृषी वापरणाऱ्या हजारो शेतकऱ्यांमध्ये सामील व्हा',
  'Get Started Today': 'आजच सुरुवात करा',

  // Farming Basics
  'Farming Knowledge Hub': 'शेती ज्ञान केंद्र',
  'Your complete visual guide to modern farming - from soil to harvest': 'मातीपासून कापणीपर्यंत शेतीचे संपूर्ण दृश्य मार्गदर्शन',
  'Search farming topics...': 'शेतीचे विषय शोधा...', 'Soil Science': 'मातीची माहिती',
  'Water Management': 'पाणी नियोजन', 'Crop Science': 'पिकांची माहिती',
  'Farm Equipment': 'शेतीची अवजारे', 'Pest & Disease': 'कीड आणि रोग',
  'Fertilizers': 'खत नियोजन', 'Season Planning': 'हंगाम नियोजन',
  'Post-Harvest': 'कापणी आणि साठवण', 'Pro Tips for Farmers': 'शेतकऱ्यांसाठी उत्तम टिप्स',
  "Farmer's Golden Rules": 'शेतकऱ्याचे सुवर्ण नियम',
  'Test soil before every planting season': 'प्रत्येक लागवड हंगामापूर्वी माती परीक्षण करा',
  'Water based on crop need, not calendar': 'कॅलेंडर नव्हे, पिकाच्या गरजेनुसार पाणी द्या',
  'Monitor fields daily for pests': 'रोज शेतात कीड तपासा',
  'Rotate crops to maintain soil health': 'माती आरोग्यासाठी पीक फेरपालट करा',
  'Keep learning new farming techniques': 'नवीन शेती तंत्र शिकत रहा',
  'Connect with local agricultural officers': 'स्थानिक कृषी अधिकाऱ्यांशी संपर्क ठेवा',

  // Guide page
  'Land Preparation': 'जमीन तयारी', 'Planting': 'लागवड', 'Irrigation': 'सिंचन',
  'Pest Management': 'किड नियंत्रण', 'Harvesting': 'कापणी',
  'Pruning': 'छाटणी', 'Disease Management': 'रोग नियंत्रण',
  'Average Yield': 'सरासरी उत्पन्न', 'Expected Profit': 'अपेक्षित नफा',
  'Growing Duration': 'वाढण्याचा कालावधी', 'Pro Tips & Best Practices': 'उत्तम टिप्स',
  'Back to Home': 'मुख्य पानावर परत',

  // Products & Calculator Specific
  'Select Product': 'उत्पादन निवडा',
  'Farm Area': 'शेतीचे क्षेत्र',
  'Total Amount': 'एकूण प्रमाण',
  'Input Parameters': 'माहिती भरा',
  'Acres': 'एकर',
  'Hectares': 'हेक्टर',
  'Unit': 'युनिट',
  'Enter farm details to calculate requirements': 'गरजा मोजण्यासाठी शेतीचा तपशील भरा',
  'Select a product to see calculated requirements for your specific farm area.': 'तुमच्या विशिष्ट शेत क्षेत्रासाठी मोजलेल्या गरजा पाहण्यासाठी उत्पादन निवडा.',
  'Optimize Your Yield': 'तुमचे उत्पन्न वाढवा',
  'Month by Month': 'महिन्यानुसार मार्गदर्शन',
  'Key Tasks for this Month': 'या महिन्यातील मुख्य कामे',
  'Annual Roadmap': 'वार्षिक आराखडा',
  'Pro Tip': 'प्रो टिप',
  'Expert Advice': 'तज्ज्ञ सल्ला',
  'Note for Farmers': 'शेतकऱ्यांसाठी सूचना',
  'This calendar is a general guide. For specific varieties and micro-climates, consult with a local Krishi Seva Kendra or agricultural expert. High precision results are achieved by maintaining a personal farm diary alongside this digital guide.': 'हे कॅलेंडर एक सामान्य मार्गदर्शक आहे. विशिष्ट जाती आणि सूक्ष्म हवामानासाठी, स्थानिक कृषी सेवा केंद्र किंवा कृषी तज्ज्ञांशी सल्लामसलत करा. या डिजिटल मार्गदर्शकासोबत वैयक्तिक शेती डायरी ठेवल्यास अधिक चांगले निकाल मिळतात.',
  'High': 'उच्च',
  'Medium': 'मध्यम',
  'Low': 'कमी',
  'January': 'जानेवारी', 'February': 'फेब्रुवारी', 'March': 'मार्च', 'April': 'एप्रिल', 'May': 'मे', 'June': 'जून',
  'July': 'जुलै', 'August': 'ऑगस्ट', 'September': 'सप्टेंबर', 'October': 'ऑक्टोबर', 'November': 'नोव्हेंबर', 'December': 'डिसेंबर',
  'Jan': 'जाने', 'Feb': 'फेब्रु', 'Mar': 'मार्च', 'Apr': 'एप्रि', 'May': 'मे', 'Jun': 'जून',
  'Jul': 'जुलै', 'Aug': 'ऑगस्ट', 'Sep': 'सप्टें', 'Oct': 'ऑक्टो', 'Nov': 'नोव्हें', 'Dec': 'डिसें',
  'Financial Support': 'आर्थिक मदत',
  'For Every Farmer': 'प्रत्येक शेतकऱ्यासाठी',
  'Search for schemes...': 'योजना शोधा...',
  'All Schemes': 'सर्व योजना',
  'Central Schemes': 'केंद्र सरकारी योजना',
  'State Schemes': 'राज्य सरकारी योजना',
  'Click for details': 'तपशील पाहण्यासाठी क्लिक करा',
  'Benefits & Financial Aid': 'फायदे आणि आर्थिक मदत',
  'Need help with': 'मदत हवी आहे का?',
  'Documentation?': 'कागदपत्रे आणि अर्ज?',
  'Applying for government schemes requires verified documents like 7/12 extract, Aadhar Card, and Bank Passbook. Visit your nearest Maha e-Seva Kendra for assistance.': 'सरकारी योजनांसाठी अर्ज करण्यासाठी ७/१२ उतारा, आधार कार्ड आणि बँक पासबुक यांसारख्या कागदपत्रांची आवश्यकता असते. मदतीसाठी तुमच्या जवळच्या महा ई-सेवा केंद्राला भेट द्या.',
  'Find Nearest Kendra': 'जवळचे केंद्र शोधा',
  'Total Beneficiaries': 'एकूण लाभार्थी',
  'Funds Disbursed': 'वितरित निधी',
  'Active Schemes': 'सक्रिय योजना',
  'Success Rate': 'यशस्वी दर',
  'Maharashtra state government\'s additional income support scheme for farmers, matching the PM-KISAN amount to double the benefit.': 'महाराष्ट्र राज्य सरकारची शेतकऱ्यांसाठी अतिरिक्त उत्पन्न आधार योजना, ज्यामध्ये पीएम-किसानच्या रकमेइतकीच मदत देऊन फायदा दुप्पट केला जातो.',
  'All farmers registered and eligible for PM-KISAN in Maharashtra.': 'महाराष्ट्रातील पीएम-किसानसाठी नोंदणीकृत आणि पात्र असलेले सर्व शेतकरी.',
  'Additional ₹6,000 per year from the state government, making it total ₹12,000 including PM-KISAN.': 'राज्य सरकारकडून अतिरिक्त ₹६,००० प्रति वर्ष, पीएम-किसानसह एकूण ₹१२,००० मिळतात.',
  'Automatic for PM-KISAN beneficiaries': 'पीएम-किसान लाभार्थ्यांसाठी स्वयंचलित',
  'PM-KUSUM scheme provides solar pumps to farmers for irrigation, reducing dependency on diesel pumps and providing day-time reliable power.': 'पीएम-कुसुम योजना शेतकऱ्यांना सिंचनासाठी सौर पंप प्रदान करते, ज्यामुळे डिझेल पंपांवरील अवलंबित्व कमी होते आणि दिवसा विश्वासार्ह वीज मिळते.',
  'Farmers with verified land records and a water source (well/borewell).': 'सत्यापित जमिनीच्या नोंदी आणि पाण्याचा स्रोत (विहीर/कूपनलिका) असलेले शेतकरी.',
  '90% to 95% subsidy on solar pump sets. Only 5-10% contribution from the farmer.': 'सौर पंप संचावर ९०% ते ९५% सबसिडी. शेतकऱ्याचा वाटा फक्त ५-१०%.',
  'Limited quotas released periodically': 'वेळोवेळी मर्यादित कोटा जाहीर केला जातो',
  'A scheme to provide farm ponds to every farmer who demands one, ensuring water security for crops during dry spells.': 'मागणी करणाऱ्या प्रत्येक शेतकऱ्याला शेततळे देण्याची योजना, ज्यामुळे कोरड्या काळात पिकांसाठी पाणी सुरक्षा सुनिश्चित होते.',
  'Minimum 0.60 hectare land ownership in Maharashtra.': 'महाराष्ट्रात किमान ०.६० हेक्टर जमीन मालकी.',
  'Direct subsidy of ₹50,000 for constructing a farm pond of standard size.': 'प्रमाणित आकाराचे शेततळे बांधण्यासाठी ₹५०,००० थेट सबसिडी.',
  'Open application via MahaDBT': 'महाडीबीटी द्वारे खुला अर्ज',
  'Insurance cover for farmers in case of accidental death or disability, providing financial security to the family.': 'अपघाती मृत्यू किंवा अपंगत्वाच्या बाबतीत शेतकऱ्यांसाठी विमा संरक्षण, कुटुंबाला आर्थिक सुरक्षा प्रदान करते.',
  'All farmers in Maharashtra aged between 10 to 75 years.': 'महाराष्ट्रातील १० ते ७५ वयोगटातील सर्व शेतकरी.',
  '₹2 Lakh for death or double limb loss; ₹1 Lakh for single limb loss.': 'मृत्यू किंवा दोन अवयव गमावल्यास ₹२ लाख; एक अवयव गमावल्यास ₹१ लाख.',
  'Submit claim within 90 days of accident': 'अपघातानंतर ९० दिवसांच्या आत दावा सादर करा',
  'Interest subsidy on short-term crop loans for farmers who repay their loans on time.': 'वेळेवर कर्ज परतफेड करणाऱ्या शेतकऱ्यांसाठी अल्पमुदत पीक कर्जावर व्याज सवलत.',
  'Farmers taking crop loans from District Central Co-op Banks or Nationalized Banks.': 'जिल्हा मध्यवर्ती सहकारी बँका किंवा राष्ट्रीयकृत बँकांकडून पीक कर्ज घेणारे शेतकरी.',
  '0% interest on loans up to ₹3 Lakh for timely repayment.': 'वेळेवर परतफेड केल्यास ₹३ लाखांपर्यंतच्या कर्जावर ०% व्याज.',
  'Bank-specific repayment dates': 'बँकेनुसार परतफेडीच्या तारखा',
  'Provides information to farmers on the nutrient status of their soil along with recommendations on appropriate dosage of fertilizers.': 'शेतकऱ्यांना त्यांच्या मातीच्या पोषक स्थितीबद्दल माहिती आणि खतांच्या योग्य मात्रेबद्दल शिफारसी देते.',
  'Detailed report on 12 critical soil parameters. Helps cut fertilizer costs by 10-25%.': 'मातीच्या १२ गंभीर घटकांचा सविस्तर अहवाल. खतांचा खर्च १०-२५% कमी करण्यास मदत करते.',
  'Comprehensive insurance cover against crop failure due to natural calamities, pests, and diseases.': 'नैसर्गिक आपत्ती, कीड आणि रोगांमुळे पिकांच्या नुकसानीविरूद्ध सर्वसमावेशक विमा संरक्षण.',
  '15 days before sowing season ends': 'पेरणी हंगाम संपण्याच्या १५ दिवस आधी',
  'Learn Modern': 'आधुनिक शेती',
  'Farming Skills': 'तंत्र शिका',
  'Search for tutorials...': 'मार्गदर्शन शोधा...',
  'All Videos': 'सर्व व्हिडिओ',
  'Trending': 'लोकप्रिय',
  'Watch Now': 'आता पहा',
  'Official Channel': 'अधिकृत चॅनेल',
  'Subscribe for Weekly': 'साप्ताहिक मार्गदर्शनासाठी',
  'Farming Guides': 'सदस्य व्हा',
  'Join 100K+ farmers who are learning to increase their income every week with our video tutorials.': 'दर आठवड्याला आमच्या व्हिडिओ ट्यूटोरियलद्वारे आपले उत्पन्न वाढवायला शिकणाऱ्या १ लाखांहून अधिक शेतकऱ्यांमध्ये सामील व्हा.',
  'These videos are sourced from official agricultural channels and expert farmers. Recommendations may vary based on local conditions. Always verify with a local expert before trying new techniques.': 'हे व्हिडिओ अधिकृत कृषी चॅनेल आणि तज्ज्ञ शेतकऱ्यांकडून घेतलेले आहेत. स्थानिक परिस्थितीनुसार शिफारसी बदलू शकतात. नवीन तंत्रे वापरण्यापूर्वी नेहमी स्थानिक तज्ज्ञांकडून खात्री करा.',
  'Step-by-step guide to maintaining your drip irrigation filters and lines.': 'तुमच्या ठिबक सिंचन फिल्टर आणि पाईप्सची देखभाल करण्यासाठी टप्प्याटप्प्याने मार्गदर्शक.',
  'How to prepare Dashparni Ark - a powerful natural pesticide at zero cost.': 'दशपर्णी अर्क कसा तयार करावा - शून्य खर्चात एक शक्तिशाली नैसर्गिक कीटकनाशक.',
  'Understanding the benefits of tissue culture sugarcane for disease resistance.': 'रोगप्रतिकारशक्तीसाठी टिश्यू कल्चर उसाचे फायदे समजून घेणे.',
  'Standards and practices required for exporting grapes to European markets.': 'युरोपियन बाजारपेठेत द्राक्षे निर्यात करण्यासाठी आवश्यक मानके आणि पद्धती.',
  'Correct way to collect soil samples for accurate lab testing results.': 'अचूक प्रयोगशाळा चाचणी निकालांसाठी मातीचे नमुने गोळा करण्याची योग्य पद्धत.',
  'A look at modern sugarcane and grape harvesting machines in action.': 'ऊस आणि द्राक्ष कापणीच्या आधुनिक यंत्रांची कार्यपद्धती.',
  'Comprehensive introduction to Zero Budget Natural Farming by experts.': 'तज्ज्ञांद्वारे झिरो बजेट नैसर्गिक शेतीची सर्वसमावेशक ओळख.',
  'Effective methods to control White Grub and Stem Borers in sugarcane.': 'उसातील हुमणी अळी आणि खोडकिडा नियंत्रित करण्याच्या प्रभावी पद्धती.',
  'Instant Profit Analysis': 'झटपट नफा विश्लेषण',
  'Fill in your farm details on the left to see detailed profit projections and ROI analysis.': 'तपशीलवार नफा अंदाज आणि ROI विश्लेषण पाहण्यासाठी डावीकडे तुमच्या शेताचा तपशील भरा.',

  // Calendar Specific
  'Smart Crop Calendar': 'स्मार्ट पीक कॅलेंडर',
  'Select your crop and track monthly activities for maximum yield': 'पीक निवडा आणि जास्तीत जास्त उत्पन्नासाठी मासिक कामे पहा',
  'Priority': 'प्राधान्य', 'Select Month': 'महिना निवडा', 'Activity': 'काम', 'Details': 'तपशील',
  'Monthly farming activities for optimal yields': 'सर्वोत्तम उत्पन्नासाठी मासिक शेती कामे',
  'Spring Planting': 'वसंत लागवड', 'Fertilizer Application': 'खत वापर',
  'Weed Control': 'तण नियंत्रण', 'Earthing Up': 'मातीलावणी',
  'Growth Monitoring': 'वाढ निरीक्षण', 'Maturity Phase': 'पक्वता टप्पा',
  'Back Pruning': 'मागे छाटणी', 'Dormancy': 'सुप्तावस्था',
  'Bud Break': 'कळी फुटणे', 'Shoot Growth': 'अंकुर वाढ', 'Flowering': 'फुलोरा',
  'Fruit Set': 'फळधारणा', 'Berry Development': 'बेरी विकास', 'Veraison': 'रंग बदल',
  'Ripening': 'पिकणे', 'Post-Harvest': 'कापणी नंतर', 'Forward Pruning': 'पुढे छाटणी',
  'High': 'जास्त', 'Medium': 'मध्यम', 'Low': 'कमी',
  'Priority Legend': 'प्राधान्य यादी',
  'Critical - Must do this month': 'अत्यावश्यक - या महिन्यात करणे आवश्यक',
  'Important - Should prioritize': 'महत्त्वाचे - प्राधान्य द्यावे',
  'Ongoing - Regular maintenance': 'नियमित - साप्ताहिक देखभाल',

  // Schemes
  'Government Schemes': 'सरकारी योजना', 'Financial assistance for farmers': 'शेतकऱ्यांसाठी आर्थिक मदत',
  'Search schemes by name...': 'नावाने योजना शोधा...', 'All Schemes': 'सर्व योजना',
  'Central': 'केंद्र', 'State': 'राज्य',
  'PM-KISAN Samman Nidhi': 'पीएम-किसान सन्मान निधी',
  'Income support of ₹6,000 per year to small and marginal farmers': 'छोट्या शेतकऱ्यांना वार्षिक ₹6,000 उत्पन्न आधार',
  'Eligibility': 'पात्रता', 'Benefits': 'फायदे', 'Application Deadline': 'अर्जाची अंतिम तारीख',
  'Apply Now': 'आता अर्ज करा', 'Click to view details': 'तपशील पाहण्यासाठी क्लिक करा',
  'Annual PM-KISAN Benefit': 'वार्षिक पीएम-किसान लाभ',
  'Micro Irrigation Subsidy': 'सूक्ष्म सिंचन अनुदान', 'Crop Insurance Premium': 'पीक विमा प्रीमियम',

  // Videos
  'Video Learning': 'व्हिडिओ शिक्षण',
  'Watch educational videos about farming techniques': 'शेती तंत्रांबद्दल शैक्षणिक व्हिडिओ पहा',
  'Search videos...': 'व्हिडिओ शोधा...',
  'Sugarcane Cultivation - Complete Guide': 'उस लागवड - संपूर्ण मार्गदर्शन',
  'Grape Farming Techniques': 'द्राक्ष शेती तंत्र',
  'Drip Irrigation for Sugarcane': 'उसासाठी ठिबक सिंचन',
  'Pest Management in Grapes': 'द्राक्षातील किड नियंत्रण',
  'Organic Farming Methods': 'सेंद्रिय शेती पद्धती',
  'Government Schemes for Farmers': 'शेतकऱ्यांसाठी सरकारी योजना',
  'Soil Health Management': 'मृदा आरोग्य व्यवस्थापन',
  'Harvesting Techniques': 'कापणी तंत्र',
  'Subscribe to Our YouTube Channel': 'आमच्या यूट्यूब चॅनेलला सदस्यता घ्या',
  'Get regular updates on farming techniques and government schemes': 'शेती तंत्र आणि सरकारी योजनांवर नियमित अपडेट मिळवा',
  'Subscribe Now': 'आता सदस्यता घ्या',

  // Help
  'Help & Support': 'मदत आणि आधार', 'Frequently Asked Questions': 'वारंवार विचारले जाणारे प्रश्न',
  'Contact Us': 'आमच्याशी संपर्क करा', 'Call Us': 'फोन करा', 'Email Us': 'ईमेल करा',
  'Live Chat': 'थेट चर्चा',

  // Auth
  'Email Address': 'ईमेल पत्ता', 'Password': 'पासवर्ड', 'Sign In': 'लॉगिन करा',
  'New to Smart Krishi?': 'स्मार्ट कृषीवर नवीन आहात?', 'Create an account': 'नवीन खाते तयार करा',
  'Full Name': 'पूर्ण नाव', 'Mobile Number (Optional)': 'मोबाईल नंबर (ऐच्छिक)',
  'Create Account': 'खाते तयार करा', 'Already have an account?': 'तुमचे आधीच खाते आहे का?',

  // Disease Detection
  'Smart Disease Detection': 'स्मार्ट पीक रोग ओळख',
  'Upload a photo of your crop to instantly identify diseases, pests, or deficiencies and get actionable remedies.': 'रोगांची, किडींची किंवा पोषक तत्वांच्या कमतरतेची त्वरित ओळख करण्यासाठी आणि खात्रीशीर उपाय मिळवण्यासाठी तुमच्या पिकाचा फोटो अपलोड करा.',
  'Click to Upload or Take Photo': 'अपलोड करण्यासाठी किंवा फोटो काढण्यासाठी क्लिक करा',
  'Analyze Image': 'फोटो तपासा', 'Primary Cause': 'मुख्य कारण', 'Precautions': 'प्रतिबंधात्मक उपाय',
  'Remedies & Treatment': 'उपाय आणि उपचार',

  // Products
  'Sugarcane Setts (Co 86032 High Yield Variety)': 'उसाची बेणी (को ८६०३२ उच्च उत्पन्न देणारी जात)',
  'Urea Fertilizer (Nitrogen 46%)': 'युरिया खत (नायट्रोजन ४६%)',
  'DAP (Di-Ammonium Phosphate)': 'डीएपी (डाय-अमोनियम फॉस्फेट)',
  'Muriate of Potash (MOP 60% K2O)': 'म्युरिएट ऑफ पोटॅश (एमओपी ६०% K2O)',
  'Chlorpyrifos 20% EC (Termite & White Grub Control)': 'क्लोरोपायरीफॉस २०% ईसी (वाळवी आणि पांढरी अळी नियंत्रण)',
  'Coragen (Chlorantraniliprole 18.5% SC) for Early Shoot Borer': 'कोराजन (खोड किडीसाठी)',
  'Atrazine 50% WP (Pre-emergence Herbicide)': 'अॅट्राझिन ५०% डब्ल्यूपी (तणनाशक)',
  'Trichoderma Viride (Bio-fungicide for Red Rot)': 'ट्रायकोडर्मा विरिडी (जैविक बुरशीनाशक)',
  'Traditional Sugarcane Harvesting Knife (Koyta)': 'उसाचा कोयता',
  'Tractor Mounted Ridger (For Earthing Up)': 'ट्रॅक्टर चलित रिजर (माती लावण्यासाठी)',
  'Grapevine Rootstock Saplings (Dog Ridge)': 'द्राक्ष कलम रोपे (डॉग रिज)',
  'NPK 00:52:34 (Mono Potassium Phosphate)': 'एनपीके ००:५२:३४ (मोनो पोटॅशियम फॉस्फेट)',
  'Gibberellic Acid (GA3) 90% Tech (Growth Regulator)': 'जिब्रेलिक ॲसिड (GA3) ९०% टेक (वाढ नियंत्रक)',
  'Chelated Micronutrient Mixture': 'चिलेटेड सूक्ष्म अन्नद्रव्य मिश्रण',
  'Wettable Sulphur 80% WP (Powdery Mildew Control)': 'वेटेबल सल्फर ८०% डब्ल्यूपी (भुूरी नियंत्रण)',
  'Copper Oxychloride 50% WP (Downy Mildew Control)': 'कॉपर ऑक्सीक्लोराईड ५०% डब्ल्यूपी (केवडा नियंत्रण)',
  'Bordeaux Mixture (Broad-spectrum Fungicide)': 'बोर्डो मिश्रण (बुरशीनाशक)',
  'How can we': 'आम्ही कशी',
  'Help You Today?': 'मदत करू शकतो?',
  'तुमचे प्रश्न इथे शोधा...': 'तुमचे प्रश्न इथे शोधा...',
  'Common': 'नेहमीचे',
  'Farmer Inquiries': 'शेतकऱ्यांचे प्रश्न',
  'Was this helpful?': 'हे उपयुक्त होते का?',
  'Verified Support': 'सत्यापित मदत',
  'Visit Your Nearest': 'तुमच्या जवळच्या',
  'Krishi Seva Kendra': 'कृषी सेवा केंद्राला भेट द्या',
  'For physical assistance with documentation and offline scheme applications, visit our partner centers across Maharashtra.': 'कागदपत्रे आणि ऑफलाइन योजना अर्जांसाठी प्रत्यक्ष मदतीसाठी, महाराष्ट्रातील आमच्या भागीदार केंद्रांना भेट द्या.',
  'Find Nearest Center': 'जवळचे केंद्र शोधा',
  'Verified Farmer': 'सत्यापित शेतकरी',
  'General Information': 'सर्वसाधारण माहिती',
  'My Managed Farms': 'माझी व्यवस्थापित शेते',
  'Register Your First Farm': 'तुमच्या पहिल्या शेताची नोंदणी करा',
  'Register New': 'नवीन नोंदणी करा',
  'Farm Plot': 'शेतीचा प्लॉट',
  'Login to Dashboard': 'डॅशबोर्डवर लॉगिन करा',
  'Join our ecosystem of digital agriculture tools designed to increase yield and ensure sustainability.': 'उत्पन्न वाढवण्यासाठी आणि शाश्वततेसाठी डिझाइन केलेल्या आमच्या डिजिटल कृषी उपकरणांच्या प्रणालीमध्ये सामील व्हा.',
  'Create New Account': 'नवीन खाते तयार करा',
  'Join the Future,': 'भविष्यात सामील व्हा,',
  'Digital Agriculture Ecosystem': 'डिजिटल कृषी प्रणाली',
  'Quick Register with Google': 'गुगलसह जलद नोंदणी',
  'Grow Your': 'वाढवा तुमची',
  'Digital Farm': 'डिजिटल शेती',
  'Save your profit history & ROI stats': 'तुमचा नफा इतिहास आणि ROI आकडेवारी जतन करा',
  'Manage multiple farm plots easily': 'एकाधिक शेती प्लॉट्स सहजपणे व्यवस्थापित करा',
  'Access personalized disease remedies': 'वैयक्तिक पीक रोग उपायांमध्ये प्रवेश मिळवा',
  'Multilingual support (English & Marathi)': 'बहुभाषिक समर्थन (इंग्रजी आणि मराठी)',
  'Welcome Back,': 'पुन्हा स्वागत आहे,',
  'Sign In to Account': 'खात्यात लॉगिन करा',
  'Verified 2026': 'सत्यापित २०२६',
  'Secure SSL': 'सुरक्षित SSL',
  '50K+ Farmers': '५० हजार+ शेतकरी',
  'Centers': 'केंद्र',
  'Districts': 'जिल्हे',
  'Experts': 'तज्ज्ञ',
  'Support 24/7': '२४/७ मदत',
  'Total Land': 'एकूण जमीन',
  'Active Farms': 'सक्रिय शेते',
  'Soil Health': 'मातीचे आरोग्य',
  'Experience': 'अनुभव',
  'Member since': 'सदस्यता दिनांक',
  'Sign Out': 'बाहेर पडा',
  'Save Changes': 'बदल जतन करा',
  'Synchronizing Farms...': 'शेतांची माहिती अद्ययावत होत आहे...',
  'Register Your First Farm': 'तुमच्या पहिल्या शेताची नोंदणी करा',
  'Save Farm': 'शेती जतन करा',
  'Discard': 'रद्द करा',
  'Plot Name': 'प्लॉटचे नाव',
  'Area (ha)': 'क्षेत्र (हेक्टर)',
  'Primary Crop': 'मुख्य पीक',
  'Location': 'ठिकाण',
  'Village / District': 'गाव / जिल्हा',
  'Access Denied': 'प्रवेश नाकारला',
  'Please login to access your personal farming dashboard and stats.': 'तुमचा वैयक्तिक शेती डॅशबोर्ड आणि आकडेवारी पाहण्यासाठी कृपया लॉगिन करा.',
  'Login Now': 'आता लॉगिन करा',
  'Revolutionizing Agriculture': 'शेतीमध्ये क्रांती घडवत आहे',
  'Cultivate The Future': 'भविष्याची मशागत करा',
  'Join Maharashtra\'s most advanced digital farming ecosystem. Increase yield, reduce risk, and maximize profits with AI.': 'महाराष्ट्रातील सर्वात प्रगत डिजिटल शेती प्रणालीमध्ये सामील व्हा. उत्पादनात वाढ करा, जोखीम कमी करा आणि AI सह जास्तीत जास्त नफा मिळवा.',
  'Start Free Journey': 'विनामूल्य प्रवास सुरू करा',
  'Watch Demo': 'डेमो पहा',
  'Cultivate': 'मशागत करा',
  'The Future': 'भविष्याची',
  'Farmers Online': 'शेतकरी ऑनलाइन',
  'Master the Art of': 'कलेमध्ये प्राविण्य मिळवा',
  'Modern Farming': 'आधुनिक शेती',
  'Your complete visual guide to agricultural excellence. Explore best practices, from soil preparation to advanced harvest techniques.': 'कृषी उत्कृष्टतेसाठी तुमचे संपूर्ण दृश्य मार्गदर्शक. माती तयार करण्यापासून ते प्रगत कापणी तंत्रापर्यंतच्या सर्वोत्तम पद्धती जाणून घ्या.',
  'Search farming topics...': 'शेतीचे विषय शोधा...',
  'Full Ecosystem': 'संपूर्ण प्रणाली',
  'Master Every Step Of Your Cultivation': 'तुमच्या शेतीच्या प्रत्येक टप्प्यात नैपुण्य मिळवा',
  'Everything from seed selection to marketplace distribution, localized for Maharashtra.': 'बियाणे निवडीपासून ते बाजारपेठेतील वितरणापर्यंत सर्व काही, खास महाराष्ट्रासाठी.',
  'Master the Art of Modern Farming': 'आधुनिक शेतीच्या कलेमध्ये प्राविण्य मिळवा',
  'Full Ecosystem': 'संपूर्ण प्रणाली',
  'Smart Crop Guides': 'स्मार्ट पीक मार्गदर्शक',
  'Expert cultivation techniques for Sugarcane, Grapes, and more.': 'ऊस, द्राक्षे आणि इतर पिकांसाठी तज्ज्ञ लागवड तंत्र.',
  'AI Tools': 'AI साधने',
  'Agri Advisor': 'कृषी सल्लागार',
  'AI-driven profit analysis and resource planning for your farm.': 'तुमच्या शेतीसाठी AI-आधारित नफा विश्लेषण आणि संसाधन नियोजन.',
  'Schedule': 'वेळापत्रक',
  'Growth Calendar': 'वाढ वेळापत्रक',
  'Dynamic schedule for watering, fertilizing, and harvesting.': 'पाणी देणे, खत घालणे आणि काढणीसाठी गतिमान वेळापत्रक.',
  'Benefits': 'फायदे',
  'Unlock subsidies and financial support from the government.': 'शासनाकडून अनुदान आणि आर्थिक मदत मिळवा.',
  'Education': 'शिक्षण',
  'Learning Hub': 'शिक्षण केंद्र',
  'Cinematic video tutorials on modern agricultural practices.': 'आधुनिक कृषी पद्धतींवर आधारित प्रभावी व्हिडिओ ट्यूटोरियल्स.',
  'Join Now for Free': 'आता मोफत सामील व्हा',
  'Knowledge Hub': 'ज्ञान केंद्र',
  'Full Ecosystem': 'संपूर्ण प्रणाली',
  'Ready to Transform Your Farm?': 'तुमची शेती बदलण्यासाठी तयार आहात?',
  'Join thousands of successful farmers who have already digitized their operations with Smart Krishi.': 'स्मार्ट कृषीसह आपल्या शेतीचे डिजिटलायझेशन केलेल्या हजारो यशस्वी शेतकऱ्यांमध्ये सामील व्हा.',
  'Built for Maharashtra\'s Soils': 'खास महाराष्ट्राच्या मातीसाठी',
  'We combine generational farming wisdom with state-of-the-art satellite data and machine learning.': 'आम्ही पिढ्यानपिढ्यांच्या शेती ज्ञानाची सांगड अत्याधुनिक सॅटेलाईट डेटा आणि मशीन लर्निंगशी घालतो.',
  'Deep localization for 36 districts': '३६ जिल्ह्यांसाठी सखोल स्थानिकीकरण',
  'Marathi-first educational experience': 'मराठी-प्रथम शैक्षणिक अनुभव',
  'Offline support for remote villages': 'दुर्गम गावांसाठी ऑफलाइन मदत',
  'Yield Growth': 'उत्पादन वाढ',
  'Accuracy Rate': 'अचूकता दर',
  'Farmer Profits': 'शेतकरी नफा',
  'Digital Guides': 'डिजिटल मार्गदर्शक',
  'Risk Reduc.': 'जोखीम घट',
  'Expert Hours': 'तज्ज्ञ वेळ',
  'Free Access': 'मोफत प्रवेश',
  'Pro Tips for Farmers': 'शेतकऱ्यांसाठी खास टिप्स',
  'Farmer\'s Golden Rules': 'शेतकऱ्यांचे सुवर्ण नियम',
  'Test soil before every planting season': 'प्रत्येक लागवडीपूर्वी माती परीक्षण करा',
  'Water based on crop need, not calendar': 'कॅलेंडरनुसार नाही, तर पिकाच्या गरजेनुसार पाणी द्या',
  'Monitor fields daily for pests': 'कीड पाहण्यासाठी दररोज शेताची पाहणी करा',
  'Rotate crops to maintain soil health': 'जमिनीचे आरोग्य टिकवण्यासाठी फेरपालट करा',
  'Keep learning new farming techniques': 'शेतीची नवीन तंत्रे शिकत राहा',
  'Connect with local agricultural officers': 'स्थानिक कृषी अधिकार्‍यांशी संपर्क ठेवा',
  'Smart Krishi': 'स्मार्ट कृषी',
  'Empowering Maharashtra farmers with smart farming solutions': 'महाराष्ट्रातील शेतकऱ्यांना स्मार्ट शेती उपायांसह सक्षम बनवणे',
  'Quick Links': 'जलद दुवे',
  'Agri Calculator': 'कृषी गणकयंत्र',
  'Contact': 'संपर्क',
  'Made with': 'द्वारे निर्मित',
  'for Indian Farmers': 'भारतीय शेतकऱ्यांसाठी',
  'Live Forecast': 'थेट हवामान अंदाज',
  'Updated': 'अद्ययावत',
  'Humidity': 'आर्द्रता',
  'Wind': 'वारा',
  'Sunrise': 'सूर्योदय',
  'Sunset': 'सूर्यास्त',
  'UV Index': 'यूव्ही इंडेक्स',
  'Clear Sky': 'निरभ्र आकाश',
  'Mainly Clear': 'मुख्यतः निरभ्र',
  'Partly Cloudy': 'अंशतः ढगाळ',
  'Overcast': 'पूर्णपणे ढगाळ',
  'Foggy': 'धुके',
  'Depositing Rime Fog': 'दाट धुके',
  'Light Drizzle': 'हलकी रिमझिम',
  'Moderate Drizzle': 'मध्यम रिमझिम',
  'Dense Drizzle': 'दाट रिमझिम',
  'Slight Rain': 'हलका पाऊस',
  'Moderate Rain': 'मध्यम पाऊस',
  'Heavy Rain': 'मुसळधार पाऊस',
  'Slight Rain Showers': 'हलक्या पावसाच्या सरी',
  'Moderate Rain Showers': 'मध्यम पावसाच्या सरी',
  'Violent Rain Showers': 'अतिमुसळधार पावसाच्या सरी',
  'Thunderstorm': 'विजांसह पाऊस',
  'Low': 'कमी',
  'Moderate': 'मध्यम',
  'High': 'जास्त',
  'Very High': 'खूप जास्त',
  'Extreme': 'अतिशय जास्त',
  '🌧️ Heavy rain expected. Delay irrigation and cover sensitive seedlings.': '🌧️ मुसळधार पावसाची शक्यता. सिंचन पुढे ढकला आणि संवेदनशील रोपांना झाकून ठेवा.',
  '🔥 Extreme heat! Deep irrigation recommended during early morning/late evening.': '🔥 प्रचंड उष्णता! पहाटे किंवा उशिरा संध्याकाळी सखोल सिंचन करण्याची शिफारस केली जाते.',
  '💧 High humidity! High risk of Powdery Mildew in grapes. Inspect crops.': '💧 उच्च आर्द्रता! द्राक्षांवर भुरी रोगाचा मोठा धोका. पिकांची पाहणी करा.',
  '🌬️ Strong winds! Avoid tall crop support work or pesticide spraying.': '🌬️ जोराचा वारा! वेलींना आधार देण्याचे काम किंवा कीटकनाशक फवारणी टाळा.',
  '✅ Ideal conditions for most farming activities today.': '✅ आज शेतीच्या बहुतेक कामांसाठी पोषक वातावरण आहे.',
  'Nagpur': 'नागपूर',
  'Aurangabad': 'औरंगाबाद',
  'Solapur': 'सोलापूर',
  'Amravati': 'अमरावती',
  'Ratnagiri': 'रत्नागिरी',
  'Jalgaon': 'जळगाव',
  'Ahmednagar': 'अहमदनगर',
  'Latur': 'लातूर',
  'Satara': 'सातारा',
  'Pune': 'पुणे',
  'Mumbai': 'मुंबई',
  'Nashik': 'नाशिक',
  'Sangli': 'सांगली',
  'Kolhapur': 'कोल्हापूर',
  'Online Assistant': 'ऑनलाइन सहाय्यक',
  'तुमचा प्रश्न इथे लिहा...': 'तुमचा प्रश्न इथे लिहा...',
  'Ask your farming question...': 'तुमचा शेतीविषयक प्रश्न विचारा...',
  'Powered by Smart AI': 'स्मार्ट AI द्वारा संचालित',
  'Clear Chat': 'चॅट साफ करा',
  'Namaste! I am your Smart Krishi AI assistant. How can I help you with your farming today?': 'नमस्ते! मी तुमचा स्मार्ट कृषी AI सहाय्यक आहे. आज मी तुम्हाला शेतीमध्ये कशी मदत करू शकतो?',
  'How to increase sugarcane yield?': 'उसाचे उत्पन्न कसे वाढवायचे?',
  'Disease symptoms in grapes': 'द्राक्षांमधील रोगाची लक्षणे',
  'Latest government schemes': 'नवीनतम सरकारी योजना',
  'Soil testing centers near me': 'माझ्या जवळील माती परीक्षण केंद्रे',
  'History cleared.': 'इतिहास साफ केला.',
  'Switch to English': 'इंग्रजीमध्ये बदला',
  'मराठी मध्ये बदला': 'मराठी मध्ये बदला',
};

const translations = {
  en: {
    'nav.home': 'Home', 'nav.farming_basics': 'Farming Basics', 'nav.crop_guide': 'Crop Guide',
    'nav.smart_advisor': 'Smart Advisor', 'nav.calendar': 'Calendar', 'nav.schemes': 'Schemes',
    'nav.videos': 'Videos', 'nav.help': 'Help', 'nav.profile': 'Profile',
    'nav.login': 'Login', 'nav.register': 'Register', 'nav.logout': 'Logout',
    'nav.disease_detection': 'Disease Detection',
    'nav.marketplace': 'Marketplace',
  },
  mr: {
    'nav.home': 'मुख्य पान', 'nav.farming_basics': 'शेतीची माहिती', 'nav.crop_guide': 'पीक सल्ला',
    'nav.smart_advisor': 'स्मार्ट सल्लागार', 'nav.calendar': 'नियोजन कॅलेंडर',
    'nav.schemes': 'सरकारी योजना', 'nav.videos': 'व्हिडिओ मार्गदर्शन',
    'nav.help': 'मदत आणि आधार', 'nav.profile': 'माझी माहिती',
    'nav.login': 'लॉगिन करा', 'nav.register': 'नवीन नोंदणी', 'nav.logout': 'बाहेर पडा',
    'nav.disease_detection': 'पीक रोग ओळख',
    'nav.marketplace': 'कृषी बाजारपेठ',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'mr' : 'en');
  };

  const t = (key) => translations[language][key] || key;

  const translateInstant = (text) => {
    if (!text || language === 'en') return text;
    // Handle potential array or object children (though they should be strings)
    const textStr = String(text).trim();
    return marathiDict[textStr] || text;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, translateInstant, marathiDict }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);